const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generateResumeReport = (userName, fileName, analysis) => {
  return new Promise((resolve, reject) => {
    try {
      const os = require("os");

const reportsDir = os.tmpdir();

      // Create reports folder if it doesn't exist
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      // Unique filename
      const pdfName = `Resume_Report_${Date.now()}.pdf`;
      const pdfPath = path.join(reportsDir, pdfName);

      const doc = new PDFDocument({
        margin: 50,
      });

      const stream = fs.createWriteStream(pdfPath);

      doc.pipe(stream);

      // ===========================
      // Title
      // ===========================
      doc
        .fontSize(24)
        .fillColor("#2563eb")
        .text("AI Resume Analyzer", {
          align: "center",
        });

      doc.moveDown();

      doc
        .fontSize(18)
        .fillColor("black")
        .text("Resume Analysis Report", {
          align: "center",
        });

      doc.moveDown(2);

      // ===========================
      // User Details
      // ===========================
      doc.fontSize(14);
      doc.text(`Name: ${userName}`);
      doc.text(`Resume: ${fileName}`);
      doc.text(`Generated On: ${new Date().toLocaleString()}`);

      doc.moveDown();

      // ===========================
      // ATS Score
      // ===========================
      doc
        .fontSize(20)
        .fillColor("green")
        .text(`ATS Score: ${analysis.atsScore}/100`);

      doc.moveDown();

      // ===========================
      // Strengths
      // ===========================
      doc.fillColor("black");
      doc.fontSize(16).text("Strengths");

      analysis.strengths.forEach((item) => {
        doc.fontSize(12).text(`• ${item}`);
      });

      doc.moveDown();

      // ===========================
      // Weaknesses
      // ===========================
      doc.fontSize(16).text("Weaknesses");

      analysis.weaknesses.forEach((item) => {
        doc.fontSize(12).text(`• ${item}`);
      });

      doc.moveDown();

      // ===========================
      // Missing Skills
      // ===========================
      doc.fontSize(16).text("Missing Skills");

      analysis.missingSkills.forEach((item) => {
        doc.fontSize(12).text(`• ${item}`);
      });

      doc.moveDown();

      // ===========================
      // Suggestions
      // ===========================
      doc.fontSize(16).text("Suggestions");

      analysis.suggestions.forEach((item) => {
        doc.fontSize(12).text(`• ${item}`);
      });

      doc.moveDown(2);

      // Footer
      doc
        .fontSize(12)
        .fillColor("gray")
        .text("Generated by AI Resume Analyzer", {
          align: "center",
        });

      doc.end();

      stream.on("finish", () => {
        resolve(pdfPath);
      });

      stream.on("error", reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = generateResumeReport;